name: starter_frontend_flutter
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.0.2
  file_picker: ^7.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter_animate: ^4.1.1+1
  flutter_chat_bubble: ^2.0.2
  flutter_linkify: ^6.0.0
  flutter_pdfview: ^1.3.2
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.5
  flutter_vector_icons: ^2.0.0
  flutter_zoom_drawer: ^3.0.4+1
  get: ^4.6.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.1.0
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  webview_flutter: ^4.0.7

flutter_native_splash:
  color: "#241f18"
  image: assets/images/logo_bootsplash.png
  color_dark: "#241f18"
  image_dark: assets/images/logo_bootsplash.png

  android_12:
    image: assets/images/logo_bootsplash.png
    icon_background_color: "#241f18"
    image_dark: assets/images/logo_bootsplash.png
    icon_background_color_dark: "#241f18"

  android: true
  ios: true
  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
